import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { Geist, Geist_Mono } from "next/font/google";
import ClientWrapper from "@/components/providers/ClientWrapper";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import DashboardHeader from "@/components/DashboardHeader";
import { Separator } from "@/components/ui/separator";
import { FadeInUp } from "@/components/ui/animate-on-scroll";
import DashboardFooter from "@/components/DashboardFooter";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Moneter | Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientWrapper>
      <SidebarProvider>
        <AppSidebar />

        <SidebarInset className="md:p-2 bg-transparent shadow-none! glassmorphism-scrollbar">
          <FadeInUp>
            <DashboardHeader />
          </FadeInUp>
          <FadeInUp delay={200} className="h-full">
            <div className="md:mt-3 md:rounded-xl py-5 px-6 min-h-full md:shadow-xl glassmorphism-scrollbar bg-gradient-to-tr! dark:from-neutral-950 dark:to-[#09002f] via-50% dark:via-[#09002f] from-[#fcfcfc] via-[#fcfcfc] to-indigo-50">
              <div className="dashboard-container">{children}</div>
            </div>
          </FadeInUp>
          <FadeInUp delay={400}>
            <DashboardFooter />
          </FadeInUp>
        </SidebarInset>
      </SidebarProvider>
    </ClientWrapper>
  );
}
